#!/data/data/com.termux/files/usr/bin/bash

# decrypt you gpg encrypted password file
# copy password
# shred file
# delte file

gpg -d -o $TMP_FILEPATH $PASSWORD_FILEPATH
password=$(jq ".[] | select(.id==\"${1}\") | .password" $TMP_FILEPATH | tr -d '"')
termux-clipboard-set $password
shred $TMP_FILEPATH
rm $TMP_FILEPATH
