#!/usr/bin/node

const fs = require("fs");
const readline = require("readline");

// coloring function and colors --Optional
function colorize(color, output) {
  return ["\033[", color, "m", output, "\033[0m"].join("");
}
const smokedSoFarColor = 91;
const numDaysSinceInitColor = 92;
const numberLeftColor = 95;

// prettier-ignore
const monthArray = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"];
const countPath = "/home/dave/.personal/smoke/count";
const logPath = "/home/dave/.personal/smoke/log/";
const monthYear = monthArray[new Date().getMonth()].concat(
  new Date().getFullYear()
);
const monthlyLogFileName = logPath + monthYear + ".log";

// Times in milliseconds since the epoch, Days, Dates etc
const initialTime = 1642335300000;
const currentTime = new Date();
const numDaysSinceInit =
  (currentTime.getTime() - initialTime) / (1000 * 60 * 60 * 24);

// How many have i smoked since starting this regimen ?
// Read from a file and overwrite that file with a new number
let smokedSoFar = Number(fs.readFileSync(countPath, "utf8"));
const numberSmoked = process.argv[2] > 0 ? Number(process.argv[2]) : 0;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});
const query = `Do you want to confirm having smoked ${numberSmoked} cigarettes? [Y/n] `;

rl.question(query, function (answer) {
  if (["Y", "y", "yes", "Yes", ""].includes(answer)) {
    if (numberSmoked) {
      smokedSoFar += numberSmoked;
      fs.writeFileSync(countPath, String(smokedSoFar));
      fs.writeFileSync(
        monthlyLogFileName,
        `Smoked ${numberSmoked} cigarettes on ${currentTime.toString()}\r\n`,
        { flag: "a" }
      );
    }
    const numberLeft = Math.floor(
      (numDaysSinceInit * 186) / 365.25 - smokedSoFar
    );

    // This is just for readibility
    // prettier-ignore
    const colorizedSmokedSoFar = colorize(smokedSoFarColor, smokedSoFar)
    //prettier-ignore
    const colorizedNumDaysSinceInit = colorize(numDaysSinceInitColor, Math.floor(numDaysSinceInit))
    // prettier-ignore
    const colorizedNumberLeft = colorize(numberLeftColor, numberLeft)

    process.stdout.write(`---------------------------------------------
You have smoked ${colorizedSmokedSoFar} cigarettes in ${colorizedNumDaysSinceInit} days
You have ${colorizedNumberLeft} cigarettes left!!
---------------------------------------------\n`);
    rl.close();
  } else {
    process.stdout.write("Good bye!\n");
    rl.close();
  }
});

rl.on("close", function () {
  process.exit(0);
});
